Repository ansible-community/pytest-molecule, pull requests merged in 2021-07, with the labels that each got.

#91 Avoid pre-release dependencies
  setup.cfg
  tox.ini
Labels: bug

#92 Enable pylint and mypy
  .pre-commit-config.yaml
  mypy.ini
Labels: skip-changelog

#93 Updated packaging testing
  pyproject.toml
  tox.ini
Labels: bug

#94 Modernized github pipelines
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: test

#96 Adopt src code layout
  .pre-commit-config.yaml
  setup.cfg
  src/pytest_molecule/__init__.py
  src/pytest_molecule/py.typed
  tox.ini
Labels: enhancement

#97 Enable isort
  .pre-commit-config.yaml
  src/pytest_molecule/__init__.py
Labels: skip-changelog

#98 Add tadeboro as code owner
  .github/CODEOWNERS
Labels: skip-changelog

#100 Avoid multiple executions on release
  .github/workflows/release.yml
Labels: skip-changelog

#99 Add ability to use xfail and skip markers
  README.rst
  src/pytest_molecule/__init__.py
  tests/roles/foo/molecule/disabled/converge.yml
  tests/roles/foo/molecule/disabled/molecule.yml
Labels: feature

#101 Remove test extra from molecule dependency
  setup.cfg
Labels: enhancement
